---1. What are the names of all the countries in the country table?
select country_name as "country Name"
from country
order by country_name asc
go
--2. What is the total number of customers in the customers table?
select count(customer_id) as "Total No.Of Customers"
from customers
go
--3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
select avg(age) as 'Average age of customer who want to receive email'
from customers
where can_email= 'yes'
go
--4. How many orders were made by customers aged 30 or older?

SELECT count(o.order_id) as "Number of orders"
from orders o join customers c 
on o.customer_id= c.customer_id
where age >=30
GO
--5. What is the total revenue generated by each product category?

SELECT p.category,sum(price) as "Total Revenue product category "
from products p join baskets o
on p.product_id = o.product_id
group by p.category
GO
--6. What is the average price of products in the 'food' category?
SELECT upper(p.category) 'food category',cast(AVG(price) as money) as 'average Price of Food items'
from products p 
WHERE category = 'food'
group by p.category
go
--7. How many orders were made in each sales channel (sales_channel column) in the orders table?
select sales_channel as 'Sales channel',count(order_id) as 'No.of orders made'
from orders
group by sales_channel
GO
--8.What is the date of the latest order made by a customer who can receive marketing emails?
SELECT top 1 max(first_shop) 'latest order date', customer_id
from customers
where can_email= 'yes'
group by customer_id 
order by customer_id  desc 
go
--9. What is the name of the country with the highest number of orders?
select top 1  c.country_name as country,count(o.order_id) as 'No.of Orders'
from  country c join orders o 
      on o.country_id = c.country_id
group by c.country_name
order by 2 DESC
go
-----------------------------
--10. What is the average age of customers who made orders in the 'vitamins' product category?
select Avg(age) as ' Average Age of customers who ordered vitamins'
from orders o join customers c 
        on o.customer_id=c.customer_id
        join baskets b on b.order_id = o.order_id
        join products p on b.product_id=p.product_id
where p.category = 'vitamins'
go
